# Generated by Django 5.2.15 on 2026-07-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='valeur_estimee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valeur estimée du bien en USD (utilisée pour la grille tarifaire).', max_digits=14, null=True),
        ),
    ]
