# Generated by Django 5.2.15 on 2026-07-16 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0002_workflow_paiement_usd'),
        ('contrats', '0007_bien_grille_tarifaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='grille_tarifaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='contrats.grilletarifaire', verbose_name="Forfait d'assurance"),
        ),
    ]
