# Generated by Django 5.2.15 on 2026-06-24 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('type_sinistre', models.CharField(choices=[('DEGAT_EAUX', 'Dégât des eaux'), ('INCENDIE', 'Incendie'), ('VOL', 'Vol'), ('TEMPETE', 'Tempête'), ('AUTRE', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('date_sinistre', models.DateField()),
                ('statut', models.CharField(choices=[('DECLARE', 'Déclaré'), ('EN_COURS', 'En cours'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='DECLARE', max_length=15)),
                ('motif_rejet', models.TextField(blank=True)),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistres', to='contrats.contrat')),
                ('declare_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinistres_declares', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinistres_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinistre',
                'verbose_name_plural': 'Sinistres',
                'ordering': ['-created_at'],
            },
        ),
    ]
