# Generated by Django 5.2.15 on 2026-07-01 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('sinistres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='montant_indemnise',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant effectivement indemnisé après validation.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='plafond_indemnisation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Plafond d'indemnisation applicable à ce sinistre.", max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='RapportIndemnisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_indemnise', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_non_couvert', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plafond_sinistre', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plafond_contrat_avant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plafond_contrat_apres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depassement_detecte', models.BooleanField(default=False)),
                ('contrat_invalide', models.BooleanField(default=False)),
                ('contenu', models.TextField()),
                ('copie_client_envoyee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_indemnisation', to='documents.document')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_indemnisation_generes', to=settings.AUTH_USER_MODEL)),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_indemnisation', to='sinistres.sinistre')),
            ],
            options={
                'verbose_name': "Rapport d'indemnisation",
                'verbose_name_plural': "Rapports d'indemnisation",
                'ordering': ['-created_at'],
            },
        ),
    ]
