# Generated by Django 5.2.15 on 2026-07-16 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_workflow_paiement_usd'),
        ('sinistres', '0003_traitement_indemnisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='document_retrait_bancaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinistres_retrait_bancaire', to='documents.document'),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='preuve_retrait_indemnisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinistres_preuve_retrait', to='documents.document'),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='statut_retrait_paiement',
            field=models.CharField(choices=[('ROUGE', 'Non indemnisé / preuve manquante'), ('VERT', 'Indemnisé — preuve fournie')], default='ROUGE', max_length=10),
        ),
    ]
