# Generated by Django 5.2.15 on 2026-06-24 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(blank=True, max_length=200)),
                ('siret', models.CharField(blank=True, max_length=14)),
                ('adresse', models.TextField(blank=True)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes_internes', models.TextField(blank=True, help_text='Visible uniquement en interne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActiviteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('CONNEXION', 'Connexion'), ('BIEN_CREE', 'Bien déclaré'), ('CONTRAT_CREE', 'Contrat créé'), ('SINISTRE_DECLARE', 'Sinistre déclaré'), ('DOCUMENT_UPLOAD', 'Document uploadé'), ('PROFIL_MODIFIE', 'Profil modifié'), ('AUTRE', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='clients.client')),
            ],
            options={
                'verbose_name': 'Activité client',
                'verbose_name_plural': 'Activités clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
