# Generated by Django 5.2.15 on 2026-07-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='montant_indemnise_cumule',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total déjà indemnisé sur ce contrat.', max_digits=12),
        ),
        migrations.AddField(
            model_name='contrat',
            name='plafond_indemnisation',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Plafond total d'indemnisation du contrat.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('RESILIE', 'Résilié'), ('EPUISE', 'Plafond épuisé')], default='BROUILLON', max_length=15),
        ),
    ]
