# Generated by Django 5.2.15 on 2026-07-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_plafonds_indemnisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='date_souscription',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
