# Generated by Django 5.2.15 on 2026-07-16 12:28

import contrats.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0002_workflow_paiement_usd'),
        ('clients', '0001_initial'),
        ('contrats', '0004_contrat_inactif_plafond'),
        ('documents', '0003_workflow_paiement_usd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrilleTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bien', models.CharField(max_length=30)),
                ('libelle', models.CharField(max_length=120)),
                ('valeur_min', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valeur_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('prime_annuelle', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plafond_indemnisation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grille tarifaire',
                'verbose_name_plural': 'Grilles tarifaires',
                'ordering': ['type_bien', 'valeur_min'],
            },
        ),
        migrations.AddField(
            model_name='contrat',
            name='bon_paiement_reference',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contrat',
            name='paiement_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('BROUILLON', 'Brouillon'), ('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('EXPIRE', 'Expiré'), ('RESILIE', 'Résilié'), ('EPUISE', 'Inactif')], default='BROUILLON', max_length=15),
        ),
        migrations.CreateModel(
            name='PoliceAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('type_assurance', models.CharField(max_length=30)),
                ('prime_annuelle', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plafond_indemnisation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polices', to='biens.bien')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polices', to='clients.client')),
                ('contrat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='police_assurance', to='contrats.contrat')),
            ],
            options={
                'verbose_name': "Police d'assurance",
                'verbose_name_plural': "Polices d'assurance",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreuvePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('fichier', models.FileField(upload_to=contrats.models.preuve_paiement_upload_path)),
                ('is_validated', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves_paiement', to='clients.client')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves_paiement', to='contrats.contrat')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preuves_paiement', to='documents.document')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preuves_paiement_deposees', to=settings.AUTH_USER_MODEL)),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preuves_paiement_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preuve de paiement',
                'verbose_name_plural': 'Preuves de paiement',
                'ordering': ['-created_at'],
            },
        ),
    ]
