# Generated by Django 5.2.15 on 2026-07-16 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0005_workflow_paiement_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='grille_tarifaire',
            field=models.ForeignKey(blank=True, help_text='Formule tarifaire sélectionnée lors de la souscription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='contrats.grilletarifaire'),
        ),
    ]
