# Generated by Django 5.2.15 on 2026-07-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0007_bien_grille_tarifaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='montant_indemnise_cumule',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total déjà indemnisé sur ce contrat (USD).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='plafond_indemnisation',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Plafond total d'indemnisation du contrat (USD).", max_digits=12),
        ),
    ]
