# Generated by Django 5.2.15 on 2026-06-24 16:48

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
        ('sinistres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('JUSTIFICATIF', 'Justificatif'), ('PHOTO', 'Photo'), ('RAPPORT', 'Rapport'), ('CONTRAT_PDF', 'Contrat PDF'), ('AUTRE', 'Autre')], default='JUSTIFICATIF', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to=documents.models.document_upload_path)),
                ('taille_octets', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='biens.bien')),
                ('sinistre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sinistres.sinistre')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
