# Generated by Django 5.2.15 on 2026-07-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_contrat_visuel_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('JUSTIFICATIF', 'Justificatif'), ('PHOTO', 'Photo'), ('RAPPORT', 'Rapport'), ('CONTRAT_PDF', 'Contrat PDF'), ('BON_PAIEMENT', 'Bon de paiement'), ('PREUVE_PAIEMENT', 'Preuve de paiement'), ('RETRAIT_BANCAIRE', 'Retrait bancaire'), ('AUTRE', 'Autre')], default='JUSTIFICATIF', max_length=20),
        ),
    ]
