# Generated by Django 5.2.15 on 2026-06-24 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionEnAttente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SINISTRE_INCOMPLET', 'Sinistre incomplet'), ('CONTRAT_NON_FINALISE', 'Contrat non finalisé'), ('DOCUMENTS_MANQUANTS', 'Documents manquants'), ('BIEN_INCOMPLET', 'Bien incomplet'), ('CONTRAT_EXPIRATION', 'Renouvellement contrat')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_en_attente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action en attente',
                'verbose_name_plural': 'Actions en attente',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_resolved'], name='notificatio_user_id_6e405a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('ACTION_PENDING', 'Action en attente'), ('STATUT_CHANGE', 'Changement de statut'), ('CONTRAT_EXPIRATION', 'Expiration contrat'), ('DIGEST', 'Résumé quotidien'), ('SYSTEM', 'Système')], max_length=25)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('critical', 'Critique')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('digest_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['digest_key'], name='notificatio_digest__c84f52_idx')],
            },
        ),
    ]
