# Generated by Django 5.2.15 on 2026-07-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionenattente',
            name='action_type',
            field=models.CharField(choices=[('SINISTRE_INCOMPLET', 'Sinistre incomplet'), ('CONTRAT_NON_FINALISE', 'Contrat non finalisé'), ('DOCUMENTS_MANQUANTS', 'Documents manquants'), ('BIEN_INCOMPLET', 'Bien incomplet'), ('CONTRAT_EXPIRATION', 'Renouvellement contrat'), ('BIEN_A_VALIDER', 'Bien à valider'), ('SINISTRE_A_TRAITER', 'Sinistre à traiter'), ('SINISTRE_A_VALIDER', 'Sinistre à valider')], max_length=25),
        ),
    ]
